version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crispy_octo_development

  redis:
    image: redis

  web:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://root@localhost:5432/crispy_octo_development
      REDIS_URL: redis://redis:6379/0
