version: "3.7"

services:
  db:
    image: "mysql:5.7"
    platform: linux/amd64
    restart: always
    env_file:
      - .env.docker
    expose:
      - "3307"
    volumes:
      - db:/var/run/mysqld
    ports:
      - "3307:3306"

  redis:
    image: redis:4.0-alpine
    command: redis-server
    env_file:
      - .env.docker
    volumes:
      - redis:/data
    ports:
      - "6380:6379"

  web:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env.docker
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"

volumes:
  db:
  bundle:
  redis: